figure('units','normalized','outerposition',[0 0 1 1])
    
set(0, 'DefaultAxesBox' , 'on'            ,...
'DefaultAxesFontName'   , 'GOST type B'   ,...
'DefaultAxesFontSize'   , 16              ,...
'DefaultAxesFontWeight' , 'bold'          ,...
'DefaultAxesFontAngle'  , 'italic'        ,...
'DefaultaxesLineWidth'  , 1.1             ,...
'DefaultPatchLineWidth' , 1.1             ,...
'DefaultTextFontName'   , 'GOST type B'   ,...
'DefaultTextFontSize'   , 16              ,...
'DefaultTextFontWeight' , 'bold'          ,...
'DefaultTextFontAngle'  , 'italic'        ,...
'DefaultLineLineWidth'  , 1.1             ,...
'Defaultfigurecolor'    , [1 1 1]);